// Generated by Scripts/generate-openapi.py; do not edit.

import OpenAPIRuntime

enum AppServerModels {
    typealias ClientRequest = Components.Schemas.ClientRequest
    typealias ServerRequest = Components.Schemas.ServerRequest
    typealias ServerNotification = Components.Schemas.ServerNotification
}

protocol ClientRequestable {
    associatedtype Params
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest
    var id: Components.Schemas.RequestId { get }
    var params: Params { get }
}

protocol ServerRequestable {
    associatedtype Params
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest
    var id: Components.Schemas.RequestId { get }
    var params: Params { get }
}

protocol ServerNotificationPayload {
    associatedtype Params
    static func build(params: Params) -> AppServerModels.ServerNotification
    var params: Params { get }
}

extension AppServerModels.ClientRequest {
    typealias Initialize = Components.Schemas.ClientRequestInitializeRequest
    typealias ThreadStart = Components.Schemas.ClientRequestThreadStartRequest
    typealias ThreadResume = Components.Schemas.ClientRequestThreadResumeRequest
    typealias ThreadFork = Components.Schemas.ClientRequestThreadForkRequest
    typealias ThreadArchive = Components.Schemas.ClientRequestThreadArchiveRequest
    typealias ThreadDelete = Components.Schemas.ClientRequestThreadDeleteRequest
    typealias ThreadUnsubscribe = Components.Schemas.ClientRequestThreadUnsubscribeRequest
    typealias ThreadIncrementElicitation = Components.Schemas.ClientRequestThreadIncrementElicitationRequest
    typealias ThreadDecrementElicitation = Components.Schemas.ClientRequestThreadDecrementElicitationRequest
    typealias ThreadNameSet = Components.Schemas.ClientRequestThreadNameSetRequest
    typealias ThreadGoalSet = Components.Schemas.ClientRequestThreadGoalSetRequest
    typealias ThreadGoalGet = Components.Schemas.ClientRequestThreadGoalGetRequest
    typealias ThreadGoalClear = Components.Schemas.ClientRequestThreadGoalClearRequest
    typealias ThreadMetadataUpdate = Components.Schemas.ClientRequestThreadMetadataUpdateRequest
    typealias ThreadSettingsUpdate = Components.Schemas.ClientRequestThreadSettingsUpdateRequest
    typealias ThreadMemoryModeSet = Components.Schemas.ClientRequestThreadMemoryModeSetRequest
    typealias MemoryReset = Components.Schemas.ClientRequestMemoryResetRequest
    typealias ThreadUnarchive = Components.Schemas.ClientRequestThreadUnarchiveRequest
    typealias ThreadCompactStart = Components.Schemas.ClientRequestThreadCompactStartRequest
    typealias ThreadShellCommand = Components.Schemas.ClientRequestThreadShellCommandRequest
    typealias ThreadApproveGuardianDeniedAction = Components.Schemas.ClientRequestThreadApproveGuardianDeniedActionRequest
    typealias ThreadBackgroundTerminalsClean = Components.Schemas.ClientRequestThreadBackgroundTerminalsCleanRequest
    typealias ThreadBackgroundTerminalsList = Components.Schemas.ClientRequestThreadBackgroundTerminalsListRequest
    typealias ThreadBackgroundTerminalsTerminate = Components.Schemas.ClientRequestThreadBackgroundTerminalsTerminateRequest
    typealias ThreadRollback = Components.Schemas.ClientRequestThreadRollbackRequest
    typealias ThreadList = Components.Schemas.ClientRequestThreadListRequest
    typealias ThreadSearch = Components.Schemas.ClientRequestThreadSearchRequest
    typealias ThreadLoadedList = Components.Schemas.ClientRequestThreadLoadedListRequest
    typealias ThreadRead = Components.Schemas.ClientRequestThreadReadRequest
    typealias ThreadTurnsList = Components.Schemas.ClientRequestThreadTurnsListRequest
    typealias ThreadTurnsItemsList = Components.Schemas.ClientRequestThreadTurnsItemsListRequest
    typealias ThreadInjectItems = Components.Schemas.ClientRequestThreadInjectItemsRequest
    typealias SkillsList = Components.Schemas.ClientRequestSkillsListRequest
    typealias SkillsExtraRootsSet = Components.Schemas.ClientRequestSkillsExtraRootsSetRequest
    typealias HooksList = Components.Schemas.ClientRequestHooksListRequest
    typealias MarketplaceAdd = Components.Schemas.ClientRequestMarketplaceAddRequest
    typealias MarketplaceRemove = Components.Schemas.ClientRequestMarketplaceRemoveRequest
    typealias MarketplaceUpgrade = Components.Schemas.ClientRequestMarketplaceUpgradeRequest
    typealias PluginList = Components.Schemas.ClientRequestPluginListRequest
    typealias PluginInstalled = Components.Schemas.ClientRequestPluginInstalledRequest
    typealias PluginRead = Components.Schemas.ClientRequestPluginReadRequest
    typealias PluginSkillRead = Components.Schemas.ClientRequestPluginSkillReadRequest
    typealias PluginShareSave = Components.Schemas.ClientRequestPluginShareSaveRequest
    typealias PluginShareUpdateTargets = Components.Schemas.ClientRequestPluginShareUpdateTargetsRequest
    typealias PluginShareList = Components.Schemas.ClientRequestPluginShareListRequest
    typealias PluginShareCheckout = Components.Schemas.ClientRequestPluginShareCheckoutRequest
    typealias PluginShareDelete = Components.Schemas.ClientRequestPluginShareDeleteRequest
    typealias AppList = Components.Schemas.ClientRequestAppListRequest
    typealias FsReadFile = Components.Schemas.ClientRequestFsReadFileRequest
    typealias FsWriteFile = Components.Schemas.ClientRequestFsWriteFileRequest
    typealias FsCreateDirectory = Components.Schemas.ClientRequestFsCreateDirectoryRequest
    typealias FsGetMetadata = Components.Schemas.ClientRequestFsGetMetadataRequest
    typealias FsReadDirectory = Components.Schemas.ClientRequestFsReadDirectoryRequest
    typealias FsRemove = Components.Schemas.ClientRequestFsRemoveRequest
    typealias FsCopy = Components.Schemas.ClientRequestFsCopyRequest
    typealias FsWatch = Components.Schemas.ClientRequestFsWatchRequest
    typealias FsUnwatch = Components.Schemas.ClientRequestFsUnwatchRequest
    typealias SkillsConfigWrite = Components.Schemas.ClientRequestSkillsConfigWriteRequest
    typealias PluginInstall = Components.Schemas.ClientRequestPluginInstallRequest
    typealias PluginUninstall = Components.Schemas.ClientRequestPluginUninstallRequest
    typealias TurnStart = Components.Schemas.ClientRequestTurnStartRequest
    typealias TurnSteer = Components.Schemas.ClientRequestTurnSteerRequest
    typealias TurnInterrupt = Components.Schemas.ClientRequestTurnInterruptRequest
    typealias ThreadRealtimeStart = Components.Schemas.ClientRequestThreadRealtimeStartRequest
    typealias ThreadRealtimeAppendAudio = Components.Schemas.ClientRequestThreadRealtimeAppendAudioRequest
    typealias ThreadRealtimeAppendText = Components.Schemas.ClientRequestThreadRealtimeAppendTextRequest
    typealias ThreadRealtimeAppendSpeech = Components.Schemas.ClientRequestThreadRealtimeAppendSpeechRequest
    typealias ThreadRealtimeStop = Components.Schemas.ClientRequestThreadRealtimeStopRequest
    typealias ThreadRealtimeListVoices = Components.Schemas.ClientRequestThreadRealtimeListVoicesRequest
    typealias ReviewStart = Components.Schemas.ClientRequestReviewStartRequest
    typealias ModelList = Components.Schemas.ClientRequestModelListRequest
    typealias ModelProviderCapabilitiesRead = Components.Schemas.ClientRequestModelProviderCapabilitiesReadRequest
    typealias ExperimentalFeatureList = Components.Schemas.ClientRequestExperimentalFeatureListRequest
    typealias PermissionProfileList = Components.Schemas.ClientRequestPermissionProfileListRequest
    typealias ExperimentalFeatureEnablementSet = Components.Schemas.ClientRequestExperimentalFeatureEnablementSetRequest
    typealias RemoteControlEnable = Components.Schemas.ClientRequestRemoteControlEnableRequest
    typealias RemoteControlDisable = Components.Schemas.ClientRequestRemoteControlDisableRequest
    typealias RemoteControlStatusRead = Components.Schemas.ClientRequestRemoteControlStatusReadRequest
    typealias RemoteControlPairingStart = Components.Schemas.ClientRequestRemoteControlPairingStartRequest
    typealias RemoteControlPairingStatus = Components.Schemas.ClientRequestRemoteControlPairingStatusRequest
    typealias RemoteControlClientList = Components.Schemas.ClientRequestRemoteControlClientListRequest
    typealias RemoteControlClientRevoke = Components.Schemas.ClientRequestRemoteControlClientRevokeRequest
    typealias CollaborationModeList = Components.Schemas.ClientRequestCollaborationModeListRequest
    typealias MockExperimentalMethod = Components.Schemas.ClientRequestMockExperimentalMethodRequest
    typealias EnvironmentAdd = Components.Schemas.ClientRequestEnvironmentAddRequest
    typealias McpServerOauthLogin = Components.Schemas.ClientRequestMcpServerOauthLoginRequest
    typealias ConfigMcpServerReload = Components.Schemas.ClientRequestConfigMcpServerReloadRequest
    typealias McpServerStatusList = Components.Schemas.ClientRequestMcpServerStatusListRequest
    typealias McpServerResourceRead = Components.Schemas.ClientRequestMcpServerResourceReadRequest
    typealias McpServerToolCall = Components.Schemas.ClientRequestMcpServerToolCallRequest
    typealias WindowsSandboxSetupStart = Components.Schemas.ClientRequestWindowsSandboxSetupStartRequest
    typealias WindowsSandboxReadiness = Components.Schemas.ClientRequestWindowsSandboxReadinessRequest
    typealias AccountLoginStart = Components.Schemas.ClientRequestAccountLoginStartRequest
    typealias AccountLoginCancel = Components.Schemas.ClientRequestAccountLoginCancelRequest
    typealias AccountLogout = Components.Schemas.ClientRequestAccountLogoutRequest
    typealias AccountRateLimitsRead = Components.Schemas.ClientRequestAccountRateLimitsReadRequest
    typealias AccountRateLimitResetCreditConsume = Components.Schemas.ClientRequestAccountRateLimitResetCreditConsumeRequest
    typealias AccountUsageRead = Components.Schemas.ClientRequestAccountUsageReadRequest
    typealias AccountSendAddCreditsNudgeEmail = Components.Schemas.ClientRequestAccountSendAddCreditsNudgeEmailRequest
    typealias FeedbackUpload = Components.Schemas.ClientRequestFeedbackUploadRequest
    typealias CommandExec = Components.Schemas.ClientRequestCommandExecRequest
    typealias CommandExecWrite = Components.Schemas.ClientRequestCommandExecWriteRequest
    typealias CommandExecTerminate = Components.Schemas.ClientRequestCommandExecTerminateRequest
    typealias CommandExecResize = Components.Schemas.ClientRequestCommandExecResizeRequest
    typealias ProcessSpawn = Components.Schemas.ClientRequestProcessSpawnRequest
    typealias ProcessWriteStdin = Components.Schemas.ClientRequestProcessWriteStdinRequest
    typealias ProcessKill = Components.Schemas.ClientRequestProcessKillRequest
    typealias ProcessResizePty = Components.Schemas.ClientRequestProcessResizePtyRequest
    typealias ConfigRead = Components.Schemas.ClientRequestConfigReadRequest
    typealias ExternalAgentConfigDetect = Components.Schemas.ClientRequestExternalAgentConfigDetectRequest
    typealias ExternalAgentConfigImport = Components.Schemas.ClientRequestExternalAgentConfigImportRequest
    typealias ConfigValueWrite = Components.Schemas.ClientRequestConfigValueWriteRequest
    typealias ConfigBatchWrite = Components.Schemas.ClientRequestConfigBatchWriteRequest
    typealias ConfigRequirementsRead = Components.Schemas.ClientRequestConfigRequirementsReadRequest
    typealias AccountRead = Components.Schemas.ClientRequestAccountReadRequest
    typealias FuzzyFileSearch = Components.Schemas.ClientRequestFuzzyFileSearchRequest
    typealias FuzzyFileSearchSessionStart = Components.Schemas.ClientRequestFuzzyFileSearchSessionStartRequest
    typealias FuzzyFileSearchSessionUpdate = Components.Schemas.ClientRequestFuzzyFileSearchSessionUpdateRequest
    typealias FuzzyFileSearchSessionStop = Components.Schemas.ClientRequestFuzzyFileSearchSessionStopRequest

    var asClientRequest: any ClientRequestable {
        switch self {
        case let .initialize(value): value
        case let .threadStart(value): value
        case let .threadResume(value): value
        case let .threadFork(value): value
        case let .threadArchive(value): value
        case let .threadDelete(value): value
        case let .threadUnsubscribe(value): value
        case let .threadIncrementElicitation(value): value
        case let .threadDecrementElicitation(value): value
        case let .threadNameSet(value): value
        case let .threadGoalSet(value): value
        case let .threadGoalGet(value): value
        case let .threadGoalClear(value): value
        case let .threadMetadataUpdate(value): value
        case let .threadSettingsUpdate(value): value
        case let .threadMemoryModeSet(value): value
        case let .memoryReset(value): value
        case let .threadUnarchive(value): value
        case let .threadCompactStart(value): value
        case let .threadShellCommand(value): value
        case let .threadApproveGuardianDeniedAction(value): value
        case let .threadBackgroundTerminalsClean(value): value
        case let .threadBackgroundTerminalsList(value): value
        case let .threadBackgroundTerminalsTerminate(value): value
        case let .threadRollback(value): value
        case let .threadList(value): value
        case let .threadSearch(value): value
        case let .threadLoadedList(value): value
        case let .threadRead(value): value
        case let .threadTurnsList(value): value
        case let .threadTurnsItemsList(value): value
        case let .threadInjectItems(value): value
        case let .skillsList(value): value
        case let .skillsExtraRootsSet(value): value
        case let .hooksList(value): value
        case let .marketplaceAdd(value): value
        case let .marketplaceRemove(value): value
        case let .marketplaceUpgrade(value): value
        case let .pluginList(value): value
        case let .pluginInstalled(value): value
        case let .pluginRead(value): value
        case let .pluginSkillRead(value): value
        case let .pluginShareSave(value): value
        case let .pluginShareUpdateTargets(value): value
        case let .pluginShareList(value): value
        case let .pluginShareCheckout(value): value
        case let .pluginShareDelete(value): value
        case let .appList(value): value
        case let .fsReadFile(value): value
        case let .fsWriteFile(value): value
        case let .fsCreateDirectory(value): value
        case let .fsGetMetadata(value): value
        case let .fsReadDirectory(value): value
        case let .fsRemove(value): value
        case let .fsCopy(value): value
        case let .fsWatch(value): value
        case let .fsUnwatch(value): value
        case let .skillsConfigWrite(value): value
        case let .pluginInstall(value): value
        case let .pluginUninstall(value): value
        case let .turnStart(value): value
        case let .turnSteer(value): value
        case let .turnInterrupt(value): value
        case let .threadRealtimeStart(value): value
        case let .threadRealtimeAppendAudio(value): value
        case let .threadRealtimeAppendText(value): value
        case let .threadRealtimeAppendSpeech(value): value
        case let .threadRealtimeStop(value): value
        case let .threadRealtimeListVoices(value): value
        case let .reviewStart(value): value
        case let .modelList(value): value
        case let .modelProviderCapabilitiesRead(value): value
        case let .experimentalFeatureList(value): value
        case let .permissionProfileList(value): value
        case let .experimentalFeatureEnablementSet(value): value
        case let .remoteControlEnable(value): value
        case let .remoteControlDisable(value): value
        case let .remoteControlStatusRead(value): value
        case let .remoteControlPairingStart(value): value
        case let .remoteControlPairingStatus(value): value
        case let .remoteControlClientList(value): value
        case let .remoteControlClientRevoke(value): value
        case let .collaborationModeList(value): value
        case let .mockExperimentalMethod(value): value
        case let .environmentAdd(value): value
        case let .mcpServerOauthLogin(value): value
        case let .configMcpServerReload(value): value
        case let .mcpServerStatusList(value): value
        case let .mcpServerResourceRead(value): value
        case let .mcpServerToolCall(value): value
        case let .windowsSandboxSetupStart(value): value
        case let .windowsSandboxReadiness(value): value
        case let .accountLoginStart(value): value
        case let .accountLoginCancel(value): value
        case let .accountLogout(value): value
        case let .accountRateLimitsRead(value): value
        case let .accountRateLimitResetCreditConsume(value): value
        case let .accountUsageRead(value): value
        case let .accountSendAddCreditsNudgeEmail(value): value
        case let .feedbackUpload(value): value
        case let .commandExec(value): value
        case let .commandExecWrite(value): value
        case let .commandExecTerminate(value): value
        case let .commandExecResize(value): value
        case let .processSpawn(value): value
        case let .processWriteStdin(value): value
        case let .processKill(value): value
        case let .processResizePty(value): value
        case let .configRead(value): value
        case let .externalAgentConfigDetect(value): value
        case let .externalAgentConfigImport(value): value
        case let .configValueWrite(value): value
        case let .configBatchWrite(value): value
        case let .configRequirementsRead(value): value
        case let .accountRead(value): value
        case let .fuzzyFileSearch(value): value
        case let .fuzzyFileSearchSessionStart(value): value
        case let .fuzzyFileSearchSessionUpdate(value): value
        case let .fuzzyFileSearchSessionStop(value): value
        }
    }
}

extension Components.Schemas.ClientRequestInitializeRequest: ClientRequestable {
    typealias Params = Components.Schemas.InitializeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .initialize(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadResumeRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadResumeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadResume(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadForkRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadForkParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadFork(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadArchiveRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadArchiveParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadArchive(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadDeleteRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadDeleteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadDelete(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadUnsubscribeRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadUnsubscribeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadUnsubscribe(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadIncrementElicitationRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadIncrementElicitationParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadIncrementElicitation(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadDecrementElicitationRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadDecrementElicitationParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadDecrementElicitation(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadNameSetRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadSetNameParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadNameSet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadGoalSetRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadGoalSetParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadGoalSet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadGoalGetRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadGoalGetParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadGoalGet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadGoalClearRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadGoalClearParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadGoalClear(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadMetadataUpdateRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadMetadataUpdateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadMetadataUpdate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadSettingsUpdateRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadSettingsUpdateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadSettingsUpdate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadMemoryModeSetRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadMemoryModeSetParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadMemoryModeSet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMemoryResetRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .memoryReset(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadUnarchiveRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadUnarchiveParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadUnarchive(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadCompactStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadCompactStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadCompactStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadShellCommandRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadShellCommandParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadShellCommand(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadApproveGuardianDeniedActionRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadApproveGuardianDeniedActionParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadApproveGuardianDeniedAction(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadBackgroundTerminalsCleanRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadBackgroundTerminalsCleanParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadBackgroundTerminalsClean(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadBackgroundTerminalsListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadBackgroundTerminalsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadBackgroundTerminalsList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadBackgroundTerminalsTerminateRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadBackgroundTerminalsTerminateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadBackgroundTerminalsTerminate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRollbackRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRollbackParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRollback(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadSearchRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadSearchParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadSearch(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadLoadedListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadLoadedListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadLoadedList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadTurnsListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadTurnsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadTurnsList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadTurnsItemsListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadTurnsItemsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadTurnsItemsList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadInjectItemsRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadInjectItemsParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadInjectItems(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestSkillsListRequest: ClientRequestable {
    typealias Params = Components.Schemas.SkillsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .skillsList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestSkillsExtraRootsSetRequest: ClientRequestable {
    typealias Params = Components.Schemas.SkillsExtraRootsSetParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .skillsExtraRootsSet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestHooksListRequest: ClientRequestable {
    typealias Params = Components.Schemas.HooksListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .hooksList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMarketplaceAddRequest: ClientRequestable {
    typealias Params = Components.Schemas.MarketplaceAddParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .marketplaceAdd(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMarketplaceRemoveRequest: ClientRequestable {
    typealias Params = Components.Schemas.MarketplaceRemoveParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .marketplaceRemove(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMarketplaceUpgradeRequest: ClientRequestable {
    typealias Params = Components.Schemas.MarketplaceUpgradeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .marketplaceUpgrade(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginListRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginInstalledRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginInstalledParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginInstalled(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginSkillReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginSkillReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginSkillRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginShareSaveRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginShareSaveParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginShareSave(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginShareUpdateTargetsRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginShareUpdateTargetsParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginShareUpdateTargets(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginShareListRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginShareListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginShareList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginShareCheckoutRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginShareCheckoutParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginShareCheckout(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginShareDeleteRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginShareDeleteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginShareDelete(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAppListRequest: ClientRequestable {
    typealias Params = Components.Schemas.AppsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .appList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsReadFileRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsReadFileParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsReadFile(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsWriteFileRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsWriteFileParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsWriteFile(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsCreateDirectoryRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsCreateDirectoryParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsCreateDirectory(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsGetMetadataRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsGetMetadataParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsGetMetadata(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsReadDirectoryRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsReadDirectoryParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsReadDirectory(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsRemoveRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsRemoveParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsRemove(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsCopyRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsCopyParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsCopy(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsWatchRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsWatchParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsWatch(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFsUnwatchRequest: ClientRequestable {
    typealias Params = Components.Schemas.FsUnwatchParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fsUnwatch(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestSkillsConfigWriteRequest: ClientRequestable {
    typealias Params = Components.Schemas.SkillsConfigWriteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .skillsConfigWrite(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginInstallRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginInstallParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginInstall(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPluginUninstallRequest: ClientRequestable {
    typealias Params = Components.Schemas.PluginUninstallParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .pluginUninstall(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestTurnStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.TurnStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .turnStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestTurnSteerRequest: ClientRequestable {
    typealias Params = Components.Schemas.TurnSteerParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .turnSteer(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestTurnInterruptRequest: ClientRequestable {
    typealias Params = Components.Schemas.TurnInterruptParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .turnInterrupt(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeAppendAudioRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeAppendAudioParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeAppendAudio(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeAppendTextRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeAppendTextParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeAppendText(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeAppendSpeechRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeAppendSpeechParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeAppendSpeech(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeStopRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeStopParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeStop(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestThreadRealtimeListVoicesRequest: ClientRequestable {
    typealias Params = Components.Schemas.ThreadRealtimeListVoicesParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .threadRealtimeListVoices(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestReviewStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.ReviewStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .reviewStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestModelListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ModelListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .modelList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestModelProviderCapabilitiesReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.ModelProviderCapabilitiesReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .modelProviderCapabilitiesRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestExperimentalFeatureListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ExperimentalFeatureListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .experimentalFeatureList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestPermissionProfileListRequest: ClientRequestable {
    typealias Params = Components.Schemas.PermissionProfileListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .permissionProfileList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestExperimentalFeatureEnablementSetRequest: ClientRequestable {
    typealias Params = Components.Schemas.ExperimentalFeatureEnablementSetParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .experimentalFeatureEnablementSet(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlEnableRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlEnableParams?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlEnable(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlDisableRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlDisableParams?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlDisable(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlStatusReadRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlStatusRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlPairingStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlPairingStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlPairingStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlPairingStatusRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlPairingStatusParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlPairingStatus(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlClientListRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlClientsListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlClientList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestRemoteControlClientRevokeRequest: ClientRequestable {
    typealias Params = Components.Schemas.RemoteControlClientsRevokeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .remoteControlClientRevoke(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestCollaborationModeListRequest: ClientRequestable {
    typealias Params = Components.Schemas.CollaborationModeListParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .collaborationModeList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMockExperimentalMethodRequest: ClientRequestable {
    typealias Params = Components.Schemas.MockExperimentalMethodParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .mockExperimentalMethod(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestEnvironmentAddRequest: ClientRequestable {
    typealias Params = Components.Schemas.EnvironmentAddParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .environmentAdd(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMcpServerOauthLoginRequest: ClientRequestable {
    typealias Params = Components.Schemas.McpServerOauthLoginParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .mcpServerOauthLogin(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestConfigMcpServerReloadRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .configMcpServerReload(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMcpServerStatusListRequest: ClientRequestable {
    typealias Params = Components.Schemas.ListMcpServerStatusParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .mcpServerStatusList(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMcpServerResourceReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.McpResourceReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .mcpServerResourceRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestMcpServerToolCallRequest: ClientRequestable {
    typealias Params = Components.Schemas.McpServerToolCallParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .mcpServerToolCall(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestWindowsSandboxSetupStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.WindowsSandboxSetupStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .windowsSandboxSetupStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestWindowsSandboxReadinessRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .windowsSandboxReadiness(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountLoginStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.LoginAccountParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountLoginStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountLoginCancelRequest: ClientRequestable {
    typealias Params = Components.Schemas.CancelLoginAccountParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountLoginCancel(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountLogoutRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountLogout(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountRateLimitsReadRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountRateLimitsRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountRateLimitResetCreditConsumeRequest: ClientRequestable {
    typealias Params = Components.Schemas.ConsumeAccountRateLimitResetCreditParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountRateLimitResetCreditConsume(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountUsageReadRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountUsageRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountSendAddCreditsNudgeEmailRequest: ClientRequestable {
    typealias Params = Components.Schemas.SendAddCreditsNudgeEmailParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountSendAddCreditsNudgeEmail(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFeedbackUploadRequest: ClientRequestable {
    typealias Params = Components.Schemas.FeedbackUploadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .feedbackUpload(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestCommandExecRequest: ClientRequestable {
    typealias Params = Components.Schemas.CommandExecParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .commandExec(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestCommandExecWriteRequest: ClientRequestable {
    typealias Params = Components.Schemas.CommandExecWriteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .commandExecWrite(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestCommandExecTerminateRequest: ClientRequestable {
    typealias Params = Components.Schemas.CommandExecTerminateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .commandExecTerminate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestCommandExecResizeRequest: ClientRequestable {
    typealias Params = Components.Schemas.CommandExecResizeParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .commandExecResize(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestProcessSpawnRequest: ClientRequestable {
    typealias Params = Components.Schemas.ProcessSpawnParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .processSpawn(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestProcessWriteStdinRequest: ClientRequestable {
    typealias Params = Components.Schemas.ProcessWriteStdinParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .processWriteStdin(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestProcessKillRequest: ClientRequestable {
    typealias Params = Components.Schemas.ProcessKillParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .processKill(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestProcessResizePtyRequest: ClientRequestable {
    typealias Params = Components.Schemas.ProcessResizePtyParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .processResizePty(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestConfigReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.ConfigReadParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .configRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestExternalAgentConfigDetectRequest: ClientRequestable {
    typealias Params = Components.Schemas.ExternalAgentConfigDetectParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .externalAgentConfigDetect(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestExternalAgentConfigImportRequest: ClientRequestable {
    typealias Params = Components.Schemas.ExternalAgentConfigImportParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .externalAgentConfigImport(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestConfigValueWriteRequest: ClientRequestable {
    typealias Params = Components.Schemas.ConfigValueWriteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .configValueWrite(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestConfigBatchWriteRequest: ClientRequestable {
    typealias Params = Components.Schemas.ConfigBatchWriteParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .configBatchWrite(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestConfigRequirementsReadRequest: ClientRequestable {
    typealias Params = OpenAPIRuntime.OpenAPIValueContainer?
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .configRequirementsRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestAccountReadRequest: ClientRequestable {
    typealias Params = Components.Schemas.GetAccountParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .accountRead(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFuzzyFileSearchRequest: ClientRequestable {
    typealias Params = Components.Schemas.FuzzyFileSearchParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fuzzyFileSearch(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFuzzyFileSearchSessionStartRequest: ClientRequestable {
    typealias Params = Components.Schemas.FuzzyFileSearchSessionStartParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fuzzyFileSearchSessionStart(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFuzzyFileSearchSessionUpdateRequest: ClientRequestable {
    typealias Params = Components.Schemas.FuzzyFileSearchSessionUpdateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fuzzyFileSearchSessionUpdate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ClientRequestFuzzyFileSearchSessionStopRequest: ClientRequestable {
    typealias Params = Components.Schemas.FuzzyFileSearchSessionStopParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ClientRequest {
        .fuzzyFileSearchSessionStop(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension AppServerModels.ServerRequest {
    typealias ItemCommandExecutionRequestApproval = Components.Schemas.ServerRequestItemCommandExecutionRequestApprovalRequest
    typealias ItemFileChangeRequestApproval = Components.Schemas.ServerRequestItemFileChangeRequestApprovalRequest
    typealias ItemToolRequestUserInput = Components.Schemas.ServerRequestItemToolRequestUserInputRequest
    typealias McpServerElicitationRequest = Components.Schemas.ServerRequestMcpServerElicitationRequestRequest
    typealias ItemPermissionsRequestApproval = Components.Schemas.ServerRequestItemPermissionsRequestApprovalRequest
    typealias ItemToolCall = Components.Schemas.ServerRequestItemToolCallRequest
    typealias AccountChatgptAuthTokensRefresh = Components.Schemas.ServerRequestAccountChatgptAuthTokensRefreshRequest
    typealias AttestationGenerate = Components.Schemas.ServerRequestAttestationGenerateRequest
    typealias ApplyPatchApproval = Components.Schemas.ServerRequestApplyPatchApprovalRequest
    typealias ExecCommandApproval = Components.Schemas.ServerRequestExecCommandApprovalRequest

    var asServerRequest: any ServerRequestable {
        switch self {
        case let .itemCommandExecutionRequestApproval(value): value
        case let .itemFileChangeRequestApproval(value): value
        case let .itemToolRequestUserInput(value): value
        case let .mcpServerElicitationRequest(value): value
        case let .itemPermissionsRequestApproval(value): value
        case let .itemToolCall(value): value
        case let .accountChatgptAuthTokensRefresh(value): value
        case let .attestationGenerate(value): value
        case let .applyPatchApproval(value): value
        case let .execCommandApproval(value): value
        }
    }
}

extension Components.Schemas.ServerRequestItemCommandExecutionRequestApprovalRequest: ServerRequestable {
    typealias Params = Components.Schemas.CommandExecutionRequestApprovalParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .itemCommandExecutionRequestApproval(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestItemFileChangeRequestApprovalRequest: ServerRequestable {
    typealias Params = Components.Schemas.FileChangeRequestApprovalParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .itemFileChangeRequestApproval(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestItemToolRequestUserInputRequest: ServerRequestable {
    typealias Params = Components.Schemas.ToolRequestUserInputParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .itemToolRequestUserInput(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestMcpServerElicitationRequestRequest: ServerRequestable {
    typealias Params = Components.Schemas.McpServerElicitationRequestParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .mcpServerElicitationRequest(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestItemPermissionsRequestApprovalRequest: ServerRequestable {
    typealias Params = Components.Schemas.PermissionsRequestApprovalParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .itemPermissionsRequestApproval(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestItemToolCallRequest: ServerRequestable {
    typealias Params = Components.Schemas.DynamicToolCallParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .itemToolCall(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestAccountChatgptAuthTokensRefreshRequest: ServerRequestable {
    typealias Params = Components.Schemas.ChatgptAuthTokensRefreshParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .accountChatgptAuthTokensRefresh(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestAttestationGenerateRequest: ServerRequestable {
    typealias Params = Components.Schemas.AttestationGenerateParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .attestationGenerate(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestApplyPatchApprovalRequest: ServerRequestable {
    typealias Params = Components.Schemas.ApplyPatchApprovalParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .applyPatchApproval(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerRequestExecCommandApprovalRequest: ServerRequestable {
    typealias Params = Components.Schemas.ExecCommandApprovalParams
    static func build(id: Components.Schemas.RequestId, params: Params) -> AppServerModels.ServerRequest {
        .execCommandApproval(.init(id: id, method: .allCases.first!, params: params))
    }
}

extension AppServerModels.ServerNotification {
    typealias Error = Components.Schemas.ServerNotificationErrorNotification
    typealias ThreadStarted = Components.Schemas.ServerNotificationThreadStartedNotification
    typealias ThreadStatusChanged = Components.Schemas.ServerNotificationThreadStatusChangedNotification
    typealias ThreadArchived = Components.Schemas.ServerNotificationThreadArchivedNotification
    typealias ThreadDeleted = Components.Schemas.ServerNotificationThreadDeletedNotification
    typealias ThreadUnarchived = Components.Schemas.ServerNotificationThreadUnarchivedNotification
    typealias ThreadClosed = Components.Schemas.ServerNotificationThreadClosedNotification
    typealias SkillsChanged = Components.Schemas.ServerNotificationSkillsChangedNotification
    typealias ThreadNameUpdated = Components.Schemas.ServerNotificationThreadNameUpdatedNotification
    typealias ThreadGoalUpdated = Components.Schemas.ServerNotificationThreadGoalUpdatedNotification
    typealias ThreadGoalCleared = Components.Schemas.ServerNotificationThreadGoalClearedNotification
    typealias ThreadSettingsUpdated = Components.Schemas.ServerNotificationThreadSettingsUpdatedNotification
    typealias ThreadTokenUsageUpdated = Components.Schemas.ServerNotificationThreadTokenUsageUpdatedNotification
    typealias TurnStarted = Components.Schemas.ServerNotificationTurnStartedNotification
    typealias HookStarted = Components.Schemas.ServerNotificationHookStartedNotification
    typealias TurnCompleted = Components.Schemas.ServerNotificationTurnCompletedNotification
    typealias HookCompleted = Components.Schemas.ServerNotificationHookCompletedNotification
    typealias TurnDiffUpdated = Components.Schemas.ServerNotificationTurnDiffUpdatedNotification
    typealias TurnPlanUpdated = Components.Schemas.ServerNotificationTurnPlanUpdatedNotification
    typealias ItemStarted = Components.Schemas.ServerNotificationItemStartedNotification
    typealias ItemAutoApprovalReviewStarted = Components.Schemas.ServerNotificationItemAutoApprovalReviewStartedNotification
    typealias ItemAutoApprovalReviewCompleted = Components.Schemas.ServerNotificationItemAutoApprovalReviewCompletedNotification
    typealias ItemCompleted = Components.Schemas.ServerNotificationItemCompletedNotification
    typealias ItemAgentMessageDelta = Components.Schemas.ServerNotificationItemAgentMessageDeltaNotification
    typealias ItemPlanDelta = Components.Schemas.ServerNotificationItemPlanDeltaNotification
    typealias CommandExecOutputDelta = Components.Schemas.ServerNotificationCommandExecOutputDeltaNotification
    typealias ProcessOutputDelta = Components.Schemas.ServerNotificationProcessOutputDeltaNotification
    typealias ProcessExited = Components.Schemas.ServerNotificationProcessExitedNotification
    typealias ItemCommandExecutionOutputDelta = Components.Schemas.ServerNotificationItemCommandExecutionOutputDeltaNotification
    typealias ItemCommandExecutionTerminalInteraction = Components.Schemas.ServerNotificationItemCommandExecutionTerminalInteractionNotification
    typealias ItemFileChangeOutputDelta = Components.Schemas.ServerNotificationItemFileChangeOutputDeltaNotification
    typealias ItemFileChangePatchUpdated = Components.Schemas.ServerNotificationItemFileChangePatchUpdatedNotification
    typealias ServerRequestResolved = Components.Schemas.ServerNotificationServerRequestResolvedNotification
    typealias ItemMcpToolCallProgress = Components.Schemas.ServerNotificationItemMcpToolCallProgressNotification
    typealias McpServerOauthLoginCompleted = Components.Schemas.ServerNotificationMcpServerOauthLoginCompletedNotification
    typealias McpServerStartupStatusUpdated = Components.Schemas.ServerNotificationMcpServerStartupStatusUpdatedNotification
    typealias AccountUpdated = Components.Schemas.ServerNotificationAccountUpdatedNotification
    typealias AccountRateLimitsUpdated = Components.Schemas.ServerNotificationAccountRateLimitsUpdatedNotification
    typealias AppListUpdated = Components.Schemas.ServerNotificationAppListUpdatedNotification
    typealias RemoteControlStatusChanged = Components.Schemas.ServerNotificationRemoteControlStatusChangedNotification
    typealias ExternalAgentConfigImportCompleted = Components.Schemas.ServerNotificationExternalAgentConfigImportCompletedNotification
    typealias FsChanged = Components.Schemas.ServerNotificationFsChangedNotification
    typealias ItemReasoningSummaryTextDelta = Components.Schemas.ServerNotificationItemReasoningSummaryTextDeltaNotification
    typealias ItemReasoningSummaryPartAdded = Components.Schemas.ServerNotificationItemReasoningSummaryPartAddedNotification
    typealias ItemReasoningTextDelta = Components.Schemas.ServerNotificationItemReasoningTextDeltaNotification
    typealias ThreadCompacted = Components.Schemas.ServerNotificationThreadCompactedNotification
    typealias ModelRerouted = Components.Schemas.ServerNotificationModelReroutedNotification
    typealias ModelVerification = Components.Schemas.ServerNotificationModelVerificationNotification
    typealias TurnModerationMetadata = Components.Schemas.ServerNotificationTurnModerationMetadataNotification
    typealias Warning = Components.Schemas.ServerNotificationWarningNotification
    typealias GuardianWarning = Components.Schemas.ServerNotificationGuardianWarningNotification
    typealias DeprecationNotice = Components.Schemas.ServerNotificationDeprecationNoticeNotification
    typealias ConfigWarning = Components.Schemas.ServerNotificationConfigWarningNotification
    typealias FuzzyFileSearchSessionUpdated = Components.Schemas.ServerNotificationFuzzyFileSearchSessionUpdatedNotification
    typealias FuzzyFileSearchSessionCompleted = Components.Schemas.ServerNotificationFuzzyFileSearchSessionCompletedNotification
    typealias ThreadRealtimeStarted = Components.Schemas.ServerNotificationThreadRealtimeStartedNotification
    typealias ThreadRealtimeItemAdded = Components.Schemas.ServerNotificationThreadRealtimeItemAddedNotification
    typealias ThreadRealtimeTranscriptDelta = Components.Schemas.ServerNotificationThreadRealtimeTranscriptDeltaNotification
    typealias ThreadRealtimeTranscriptDone = Components.Schemas.ServerNotificationThreadRealtimeTranscriptDoneNotification
    typealias ThreadRealtimeOutputAudioDelta = Components.Schemas.ServerNotificationThreadRealtimeOutputAudioDeltaNotification
    typealias ThreadRealtimeSdp = Components.Schemas.ServerNotificationThreadRealtimeSdpNotification
    typealias ThreadRealtimeError = Components.Schemas.ServerNotificationThreadRealtimeErrorNotification
    typealias ThreadRealtimeClosed = Components.Schemas.ServerNotificationThreadRealtimeClosedNotification
    typealias WindowsWorldWritableWarning = Components.Schemas.ServerNotificationWindowsWorldWritableWarningNotification
    typealias WindowsSandboxSetupCompleted = Components.Schemas.ServerNotificationWindowsSandboxSetupCompletedNotification
    typealias AccountLoginCompleted = Components.Schemas.ServerNotificationAccountLoginCompletedNotification

    var asServerNotification: any ServerNotificationPayload {
        switch self {
        case let .error(value): value
        case let .threadStarted(value): value
        case let .threadStatusChanged(value): value
        case let .threadArchived(value): value
        case let .threadDeleted(value): value
        case let .threadUnarchived(value): value
        case let .threadClosed(value): value
        case let .skillsChanged(value): value
        case let .threadNameUpdated(value): value
        case let .threadGoalUpdated(value): value
        case let .threadGoalCleared(value): value
        case let .threadSettingsUpdated(value): value
        case let .threadTokenUsageUpdated(value): value
        case let .turnStarted(value): value
        case let .hookStarted(value): value
        case let .turnCompleted(value): value
        case let .hookCompleted(value): value
        case let .turnDiffUpdated(value): value
        case let .turnPlanUpdated(value): value
        case let .itemStarted(value): value
        case let .itemAutoApprovalReviewStarted(value): value
        case let .itemAutoApprovalReviewCompleted(value): value
        case let .itemCompleted(value): value
        case let .itemAgentMessageDelta(value): value
        case let .itemPlanDelta(value): value
        case let .commandExecOutputDelta(value): value
        case let .processOutputDelta(value): value
        case let .processExited(value): value
        case let .itemCommandExecutionOutputDelta(value): value
        case let .itemCommandExecutionTerminalInteraction(value): value
        case let .itemFileChangeOutputDelta(value): value
        case let .itemFileChangePatchUpdated(value): value
        case let .serverRequestResolved(value): value
        case let .itemMcpToolCallProgress(value): value
        case let .mcpServerOauthLoginCompleted(value): value
        case let .mcpServerStartupStatusUpdated(value): value
        case let .accountUpdated(value): value
        case let .accountRateLimitsUpdated(value): value
        case let .appListUpdated(value): value
        case let .remoteControlStatusChanged(value): value
        case let .externalAgentConfigImportCompleted(value): value
        case let .fsChanged(value): value
        case let .itemReasoningSummaryTextDelta(value): value
        case let .itemReasoningSummaryPartAdded(value): value
        case let .itemReasoningTextDelta(value): value
        case let .threadCompacted(value): value
        case let .modelRerouted(value): value
        case let .modelVerification(value): value
        case let .turnModerationMetadata(value): value
        case let .warning(value): value
        case let .guardianWarning(value): value
        case let .deprecationNotice(value): value
        case let .configWarning(value): value
        case let .fuzzyFileSearchSessionUpdated(value): value
        case let .fuzzyFileSearchSessionCompleted(value): value
        case let .threadRealtimeStarted(value): value
        case let .threadRealtimeItemAdded(value): value
        case let .threadRealtimeTranscriptDelta(value): value
        case let .threadRealtimeTranscriptDone(value): value
        case let .threadRealtimeOutputAudioDelta(value): value
        case let .threadRealtimeSdp(value): value
        case let .threadRealtimeError(value): value
        case let .threadRealtimeClosed(value): value
        case let .windowsWorldWritableWarning(value): value
        case let .windowsSandboxSetupCompleted(value): value
        case let .accountLoginCompleted(value): value
        }
    }
}

extension Components.Schemas.ServerNotificationErrorNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ErrorNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .error(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadStatusChangedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadStatusChangedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadStatusChanged(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadArchivedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadArchivedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadArchived(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadDeletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadDeletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadDeleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadUnarchivedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadUnarchivedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadUnarchived(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadClosedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadClosedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadClosed(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationSkillsChangedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.SkillsChangedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .skillsChanged(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadNameUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadNameUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadNameUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadGoalUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadGoalUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadGoalUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadGoalClearedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadGoalClearedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadGoalCleared(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadSettingsUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadSettingsUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadSettingsUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadTokenUsageUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadTokenUsageUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadTokenUsageUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationTurnStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TurnStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .turnStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationHookStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.HookStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .hookStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationTurnCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TurnCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .turnCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationHookCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.HookCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .hookCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationTurnDiffUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TurnDiffUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .turnDiffUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationTurnPlanUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TurnPlanUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .turnPlanUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ItemStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemAutoApprovalReviewStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ItemGuardianApprovalReviewStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemAutoApprovalReviewStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemAutoApprovalReviewCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ItemGuardianApprovalReviewCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemAutoApprovalReviewCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ItemCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemAgentMessageDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.AgentMessageDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemAgentMessageDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemPlanDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.PlanDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemPlanDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationCommandExecOutputDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.CommandExecOutputDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .commandExecOutputDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationProcessOutputDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ProcessOutputDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .processOutputDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationProcessExitedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ProcessExitedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .processExited(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemCommandExecutionOutputDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.CommandExecutionOutputDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemCommandExecutionOutputDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemCommandExecutionTerminalInteractionNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TerminalInteractionNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemCommandExecutionTerminalInteraction(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemFileChangeOutputDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.FileChangeOutputDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemFileChangeOutputDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemFileChangePatchUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.FileChangePatchUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemFileChangePatchUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationServerRequestResolvedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ServerRequestResolvedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .serverRequestResolved(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemMcpToolCallProgressNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.McpToolCallProgressNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemMcpToolCallProgress(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationMcpServerOauthLoginCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.McpServerOauthLoginCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .mcpServerOauthLoginCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationMcpServerStartupStatusUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.McpServerStatusUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .mcpServerStartupStatusUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationAccountUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.AccountUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .accountUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationAccountRateLimitsUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.AccountRateLimitsUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .accountRateLimitsUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationAppListUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.AppListUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .appListUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationRemoteControlStatusChangedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.RemoteControlStatusChangedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .remoteControlStatusChanged(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationExternalAgentConfigImportCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ExternalAgentConfigImportCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .externalAgentConfigImportCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationFsChangedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.FsChangedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .fsChanged(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemReasoningSummaryTextDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ReasoningSummaryTextDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemReasoningSummaryTextDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemReasoningSummaryPartAddedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ReasoningSummaryPartAddedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemReasoningSummaryPartAdded(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationItemReasoningTextDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ReasoningTextDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .itemReasoningTextDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadCompactedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ContextCompactedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadCompacted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationModelReroutedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ModelReroutedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .modelRerouted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationModelVerificationNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ModelVerificationNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .modelVerification(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationTurnModerationMetadataNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.TurnModerationMetadataNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .turnModerationMetadata(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationWarningNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.WarningNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .warning(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationGuardianWarningNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.GuardianWarningNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .guardianWarning(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationDeprecationNoticeNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.DeprecationNoticeNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .deprecationNotice(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationConfigWarningNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ConfigWarningNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .configWarning(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationFuzzyFileSearchSessionUpdatedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.FuzzyFileSearchSessionUpdatedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .fuzzyFileSearchSessionUpdated(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationFuzzyFileSearchSessionCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.FuzzyFileSearchSessionCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .fuzzyFileSearchSessionCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeStartedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeStartedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeStarted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeItemAddedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeItemAddedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeItemAdded(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeTranscriptDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeTranscriptDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeTranscriptDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeTranscriptDoneNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeTranscriptDoneNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeTranscriptDone(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeOutputAudioDeltaNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeOutputAudioDeltaNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeOutputAudioDelta(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeSdpNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeSdpNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeSdp(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeErrorNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeErrorNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeError(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationThreadRealtimeClosedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.ThreadRealtimeClosedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .threadRealtimeClosed(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationWindowsWorldWritableWarningNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.WindowsWorldWritableWarningNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .windowsWorldWritableWarning(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationWindowsSandboxSetupCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.WindowsSandboxSetupCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .windowsSandboxSetupCompleted(.init(method: .allCases.first!, params: params))
    }
}

extension Components.Schemas.ServerNotificationAccountLoginCompletedNotification: ServerNotificationPayload {
    typealias Params = Components.Schemas.AccountLoginCompletedNotification
    static func build(params: Params) -> AppServerModels.ServerNotification {
        .accountLoginCompleted(.init(method: .allCases.first!, params: params))
    }
}
